rootProject.name = "java-core-exercises"
include("exercise1")
project(":exercise1").projectDir = file("src/exercise1")
include("exercise2")
project(":exercise2").projectDir = file("src/exercise2")
include("exercise3")
project(":exercise3").projectDir = file("src/exercise3")
include("exercise4")
project(":exercise4").projectDir = file("src/exercise4")
include("exercise5")
project(":exercise5").projectDir = file("src/exercise5")
include("exercise6")
project(":exercise6").projectDir = file("src/exercise6")
include("exercise7")
project(":exercise7").projectDir = file("src/exercise7")
include("exercise8")
project(":exercise8").projectDir = file("src/exercise8")
include("exercise9")
project(":exercise9").projectDir = file("src/exercise9")
include("exercise10")
project(":exercise10").projectDir = file("src/exercise10")
